### PR TITLE
Add images for links that have thumbnails

### PR DESCRIPTION
**Pull request by MaazAli**
Renders an image for links that have thumbnails. It borrows it's code from the Instagram renderer since that essentially does the same thing.

### CODE REVIEW

**Comment by gdub22** [comment]
So this is a change to the compiler, which is a separate repo.  Right now the compiler is manually updated in this repo.  Looking into using npm to pull in the code...

**Comment by MaazAli** [comment]
Oops, okay so I should make these changes in that repo and send in a pull request there?

**Comment by gdub22** [comment]
@MaazAli hold off for now.  In looking at that repo I had some unpushed commits that remove all the embed rendering stuff from there.  I believe I refactored it out of there with the idea to move it here because it's more presentation than data.

**Comment by gdub22** [comment]
This has been added another way

**Pull request closed without merging**
